python my_clf.py \
  --task_name=XNLI \
  --do_train=true \
  --do_eval=true \
  --data_dir=./data/my_sim \
  --vocab_file=./chinese_L-12_H-768_A-12/vocab.txt \
  --bert_config_file=./chinese_L-12_H-768_A-12/bert_config.json \
  --init_checkpoint=./chinese_L-12_H-768_A-12/bert_model.ckpt \
  --max_seq_length=128 \
  --train_batch_size=16 \
  --learning_rate=5e-5 \
  --num_train_epochs=4 \
  --output_dir=./output/my_sim/
